services:
  backend:
    image: node:alpine
    volumes:
      - ./app:/app
    working_dir: /app
    command: sh -c "npm install && node migrate.js && npm run dev"
    ports:
      - "3000:3000"
    depends_on:
      - db

  frontend:
    image: node:alpine
    volumes:
      - ./client:/client
    working_dir: /client
    command: sh -c "npm install -g @angular/cli && npm install && ng serve --host 0.0.0.0"
    ports:
      - "4200:4200"
    depends_on:
      - backend

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db-data:
