services:
  backend:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./app:/app
    command: sh -c "npm install && node server.js"
    ports:
      - "3000:3000"
    depends_on:
      - db

  frontend:
    image: node:18-alpine
    working_dir: /client
    volumes:
      - ./client:/client
    command: sh -c "npm install -g @angular/cli && npm install && ng serve --host 0.0.0.0"
    ports:
      - "4200:4200"
    depends_on:
      - backend

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db-data:
